import assert from "node:assert/strict";
import { spawn } from "node:child_process";
import { mkdtemp, readFile, rm, stat, writeFile } from "node:fs/promises";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { randomUUID } from "node:crypto";
import test from "node:test";

import { createPostgresDatabase } from "../packages/database/src/node-runtime.mjs";
import { holdUlcLinzM5ExportedSnapshot } from "./ulc-linz-m5-exported-snapshot.mjs";

const databaseUrl = process.env.DATABASE_URL;
const postgresImage = "postgres:18-alpine@sha256:9a8afca54e7861fd90fab5fdf4c42477a6b1cb7d293595148e674e0a3181de15";

if (typeof databaseUrl !== "string" || databaseUrl.length === 0) {
  throw new Error("DATABASE_URL is required for the M5 exported snapshot PostgreSQL regression test.");
}

test("PostgreSQL accepts transaction characteristics before reads and rejects changing them after a read", async () => {
  const database = createPostgresDatabase(databaseUrl);
  try {
    await database.client.begin(async (sql) => {
      await sql.unsafe("SET TRANSACTION ISOLATION LEVEL REPEATABLE READ, READ ONLY");
      const rows = await sql.unsafe("SELECT pg_export_snapshot() AS snapshot_id");
      assert.equal(Array.isArray(rows), true);
      assert.equal(rows.length, 1);
      assert.match(rows[0].snapshot_id, /^[0-9A-Fa-f]{8}-[0-9A-Fa-f]{8}-[1-9][0-9]*$/);
    });

    await assert.rejects(
      database.client.begin(async (sql) => {
        await sql.unsafe("SELECT 1");
        await sql.unsafe("SET TRANSACTION ISOLATION LEVEL REPEATABLE READ, READ ONLY");
      }),
      /SET TRANSACTION ISOLATION LEVEL must be called before any query|transaction characteristics|active SQL transaction/i,
    );
  } finally {
    await database.client.end().catch(() => {});
  }
});

test("M5 backup principal inventory, exported snapshot, pg_dump and pg_restore work together on real PostgreSQL catalogs", async () => {
  const suffix = randomUUID().replaceAll("-", "").slice(0, 18);
  const sourceDatabaseName = `m5_source_${suffix}`;
  const restoreDatabaseName = `m5_restore_${suffix}`;
  const backupRole = `m5_backup_${suffix}`;
  const backupPassword = `m5${randomUUID().replaceAll("-", "")}`;
  const work = await mkdtemp(join(tmpdir(), "appbasis-m5-pg-"));
  const snapshotPath = join(work, "source.snapshot");
  const releasePath = join(work, "source.snapshot.release");
  const dumpPath = join(work, "production.pgdump");
  const admin = createPostgresDatabase(databaseUrl);
  let sourceDatabase;
  let restoreDatabase;
  let sourceCreated = false;
  let restoreCreated = false;
  let roleCreated = false;

  try {
    await admin.client.unsafe(`CREATE ROLE ${identifier(backupRole)} LOGIN PASSWORD ${literal(backupPassword)} NOSUPERUSER NOCREATEDB NOCREATEROLE NOREPLICATION NOBYPASSRLS`);
    roleCreated = true;
    await admin.client.unsafe(`CREATE DATABASE ${identifier(sourceDatabaseName)}`);
    sourceCreated = true;
    await admin.client.unsafe(`CREATE DATABASE ${identifier(restoreDatabaseName)}`);
    restoreCreated = true;
    await admin.client.unsafe(`GRANT CONNECT ON DATABASE ${identifier(sourceDatabaseName)} TO ${identifier(backupRole)}`);

    const sourceAdminUrl = databaseUrlFor(databaseUrl, sourceDatabaseName);
    sourceDatabase = createPostgresDatabase(sourceAdminUrl);
    await sourceDatabase.client.unsafe("CREATE SCHEMA m5_runtime");
    await sourceDatabase.client.unsafe("CREATE TABLE m5_runtime.snapshot_fixture (id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, payload text NOT NULL)");
    await sourceDatabase.client.unsafe("CREATE INDEX snapshot_fixture_payload_idx ON m5_runtime.snapshot_fixture (payload)");
    await sourceDatabase.client.unsafe("INSERT INTO m5_runtime.snapshot_fixture (payload) VALUES ('alpha'), ('beta'), ('gamma')");
    await sourceDatabase.client.unsafe("REVOKE ALL ON SCHEMA m5_runtime FROM PUBLIC");
    await sourceDatabase.client.unsafe(`GRANT USAGE ON SCHEMA m5_runtime TO ${identifier(backupRole)}`);
    await sourceDatabase.client.unsafe(`GRANT SELECT ON ALL TABLES IN SCHEMA m5_runtime TO ${identifier(backupRole)}`);
    await sourceDatabase.client.unsafe(`GRANT SELECT ON ALL SEQUENCES IN SCHEMA m5_runtime TO ${identifier(backupRole)}`);

    const backupUrl = databaseUrlFor(databaseUrl, sourceDatabaseName, {
      username: backupRole,
      password: backupPassword,
    });
    const snapshotPromise = holdUlcLinzM5ExportedSnapshot({
      databaseUrl: backupUrl,
      snapshotPath,
      releasePath,
    });

    let snapshotId;
    try {
      snapshotId = await waitForSnapshot(snapshotPath);
      await runPostgresContainer({
        environment: {
          DATABASE_URL: backupUrl,
          DATABASE_SNAPSHOT: snapshotId,
        },
        work,
        command: "pg_dump --format=custom --no-owner --snapshot=\"$DATABASE_SNAPSHOT\" --dbname=\"$DATABASE_URL\" --file=/evidence/production.pgdump",
      });
      assert.ok((await stat(dumpPath)).size > 0);
    } finally {
      await writeFile(releasePath, "released\n", { encoding: "utf8", mode: 0o600 }).catch(() => {});
    }
    assert.equal(await snapshotPromise, snapshotId);

    const restoreAdminUrl = databaseUrlFor(databaseUrl, restoreDatabaseName);
    await runPostgresContainer({
      environment: { DATABASE_URL: restoreAdminUrl },
      work,
      command: "pg_restore --single-transaction --no-owner --exit-on-error --dbname=\"$DATABASE_URL\" /evidence/production.pgdump",
    });

    restoreDatabase = createPostgresDatabase(restoreAdminUrl);
    const restoredRows = await restoreDatabase.client.unsafe("SELECT id, payload FROM m5_runtime.snapshot_fixture ORDER BY id");
    assert.deepEqual(
      restoredRows.map((row) => ({ id: Number(row.id), payload: row.payload })),
      [
        { id: 1, payload: "alpha" },
        { id: 2, payload: "beta" },
        { id: 3, payload: "gamma" },
      ],
    );
    const catalogRows = await restoreDatabase.client.unsafe(`
      SELECT
        to_regclass('m5_runtime.snapshot_fixture_pkey') IS NOT NULL AS primary_index_restored,
        to_regclass('m5_runtime.snapshot_fixture_id_seq') IS NOT NULL AS sequence_restored,
        (SELECT relacl IS NULL FROM pg_catalog.pg_class WHERE oid = to_regclass('m5_runtime.snapshot_fixture_pkey')) AS index_acl_is_null
    `);
    assert.deepEqual(catalogRows, [{
      primary_index_restored: true,
      sequence_restored: true,
      index_acl_is_null: true,
    }]);
  } finally {
    await restoreDatabase?.client.end().catch(() => {});
    await sourceDatabase?.client.end().catch(() => {});
    if (restoreCreated) await dropDatabase(admin, restoreDatabaseName);
    if (sourceCreated) await dropDatabase(admin, sourceDatabaseName);
    if (roleCreated) await admin.client.unsafe(`DROP ROLE IF EXISTS ${identifier(backupRole)}`).catch(() => {});
    await admin.client.end().catch(() => {});
    await rm(work, { recursive: true, force: true }).catch(() => {});
  }
});

async function waitForSnapshot(snapshotPath) {
  for (let attempt = 0; attempt < 300; attempt += 1) {
    try {
      const snapshotId = (await readFile(snapshotPath, "utf8")).trim();
      if (snapshotId.length > 0) return snapshotId;
    } catch (error) {
      if (error?.code !== "ENOENT") throw error;
    }
    await new Promise((resolve) => setTimeout(resolve, 100));
  }
  throw new Error("M5 exported snapshot was not created by the real PostgreSQL rehearsal.");
}

async function runPostgresContainer({ environment, work, command }) {
  const dockerEnvironment = { ...process.env, ...environment };
  const args = ["run", "--rm", "--network", "host"];
  for (const name of Object.keys(environment)) {
    args.push("--env", name);
  }
  args.push(
    "--volume",
    `${work}:/evidence`,
    postgresImage,
    "sh",
    "-ceu",
    command,
  );

  await new Promise((resolvePromise, rejectPromise) => {
    const child = spawn("docker", args, {
      env: dockerEnvironment,
      stdio: ["ignore", "ignore", "pipe"],
    });
    let stderr = "";
    child.stderr.setEncoding("utf8");
    child.stderr.on("data", (chunk) => {
      if (stderr.length < 4096) stderr += chunk;
    });
    child.once("error", () => rejectPromise(new Error("M5 PostgreSQL rehearsal could not start the pinned PostgreSQL container.")));
    child.once("close", (code) => {
      if (code === 0) {
        resolvePromise();
        return;
      }
      const diagnostic = stderr.replaceAll(/postgres(?:ql)?:\/\/[^\s]+/gi, "[database-url-redacted]").trim();
      rejectPromise(new Error(`M5 PostgreSQL rehearsal container failed${diagnostic ? `: ${diagnostic}` : "."}`));
    });
  });
}

async function dropDatabase(admin, databaseName) {
  await admin.client.unsafe(`SELECT pg_terminate_backend(pid) FROM pg_catalog.pg_stat_activity WHERE datname = ${literal(databaseName)} AND pid <> pg_backend_pid()`);
  await admin.client.unsafe(`DROP DATABASE IF EXISTS ${identifier(databaseName)}`);
}

function databaseUrlFor(baseUrl, databaseName, credentials = {}) {
  const url = new URL(baseUrl);
  url.pathname = `/${databaseName}`;
  if (credentials.username !== undefined) url.username = credentials.username;
  if (credentials.password !== undefined) url.password = credentials.password;
  return url.toString();
}

function identifier(value) {
  if (!/^[a-z][a-z0-9_]{0,62}$/.test(value)) {
    throw new Error("Unsafe PostgreSQL test identifier.");
  }
  return `\"${value}\"`;
}

function literal(value) {
  if (typeof value !== "string" || value.length > 128) {
    throw new Error("Unsafe PostgreSQL test literal.");
  }
  return `'${value.replaceAll("'", "''")}'`;
}
